services:
  controller:
    build: ./controller
    container_name: controller
    environment:
      - HMAC_SECRET=${HMAC_SECRET}
      - ALLOWLIST_PATH=/opt/security/config/allowlist.yaml
    volumes:
      - shared_data:/data
      - ./risk_engine/config:/opt/security/config:ro
    networks:
      - security_net

  risk-engine:
    build: ./risk_engine
    container_name: risk-engine
    environment:
      - ALLOWLIST_PATH=/opt/security/config/allowlist.yaml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - shared_data:/data
      - ./risk_engine/config:/opt/security/config:ro
    depends_on:
      - controller
    networks:
      - security_net

  dashboard:
    build: ./dashboard
    container_name: dashboard
    ports:
      - "5001:5000"
    volumes:
      - shared_data:/data
    depends_on:
      - risk-engine
    networks:
      - security_net

  node1:
    build: ./node_agent
    container_name: node1
    environment:
      - NODE_NAME=node1
      - HMAC_SECRET=${HMAC_SECRET}
      - NODE_PEER_IPS=172.20.0.1,172.20.0.2,172.20.0.3,172.20.0.4
      - PROCESS_POLICY_PATH=/opt/security/config/process_policy.yaml
      - CONFIG_HASHES_PATH=/opt/security/config/config_hashes.yaml
    volumes:
      - ./risk_engine/config:/opt/security/config:ro
    depends_on:
      - controller
    networks:
      - security_net

  node2:
    build: ./node_agent
    container_name: node2
    environment:
      - NODE_NAME=node2
      - HMAC_SECRET=${HMAC_SECRET}
      - NODE_PEER_IPS=172.20.0.1,172.20.0.2,172.20.0.3,172.20.0.4
      - PROCESS_POLICY_PATH=/opt/security/config/process_policy.yaml
      - CONFIG_HASHES_PATH=/opt/security/config/config_hashes.yaml
    volumes:
      - ./risk_engine/config:/opt/security/config:ro
    depends_on:
      - controller
    networks:
      - security_net

  node3:
    build: ./node_agent
    container_name: node3
    environment:
      - NODE_NAME=node3
      - HMAC_SECRET=${HMAC_SECRET}
      - NODE_PEER_IPS=172.20.0.1,172.20.0.2,172.20.0.3,172.20.0.4
      - PROCESS_POLICY_PATH=/opt/security/config/process_policy.yaml
      - CONFIG_HASHES_PATH=/opt/security/config/config_hashes.yaml
    volumes:
      - ./risk_engine/config:/opt/security/config:ro
    depends_on:
      - controller
    networks:
      - security_net

  node4:
    build: ./node_agent
    container_name: node4
    environment:
      - NODE_NAME=node4
      - HMAC_SECRET=${HMAC_SECRET}
      - NODE_PEER_IPS=172.20.0.1,172.20.0.2,172.20.0.3,172.20.0.4
      - PROCESS_POLICY_PATH=/opt/security/config/process_policy.yaml
      - CONFIG_HASHES_PATH=/opt/security/config/config_hashes.yaml
    volumes:
      - ./risk_engine/config:/opt/security/config:ro
    depends_on:
      - controller
    networks:
      - security_net

  wazuh:
    build: ./wazuh
    container_name: wazuh
    volumes:
      - shared_data:/data
    networks:
      - security_net

networks:
  security_net:
    driver: bridge

volumes:
  shared_data:
